### ISSUE TITLE
Room Needs id

### ISSUE THREAD

**Issue by CheezBoiger** [MichaelWallace30/schedulerCS356#1]
Room Class doesn't have an Id parameter. I need it to access the Room Id from the data base for admin.

**Comment by CheezBoiger** [comment]
Oh, nevermind, it doesn't need one.

**Comment by MichaelWallace30** [comment]
I can add it but room number us unique

**Comment by CheezBoiger** [comment]
nah, it's cool, i was just wondering, but yea the room number is unique

**Comment by CheezBoiger** [comment]
I forgot about that, lulz.
