### ISSUE TITLE
Meeting ID doesn't drop in Account Meeting List

### ISSUE THREAD

**Issue by CheezBoiger** [MichaelWallace30/schedulerCS356#3]
the meeting is deleted from the MEETINGS table, and it's tables are deleted afterwards, but for some reason it is not deleting from account meetings, and their tables.

**Comment by CheezBoiger** [comment]
Problem is in the schedulers.

**Comment by CheezBoiger** [comment]
It gets added in Schedule table, but when meeting is deleted, it seems like the schedule can't find the owner id?

**Comment by CheezBoiger** [comment]
problem has been fixed.

**Comment by CheezBoiger** [comment]
Actually, account meeting table still holds the meeting id when it was deleted. This can raise some concerns of keeping garbage data.

**Comment by CheezBoiger** [comment]
Everything else works fine though

**Comment by MichaelWallace30** [comment]
removeObject(Meeting)?

**Comment by MichaelWallace30** [comment]
ok removeObject(Meeting) will remove the meeting from the accounts list an update the account on the db.
