### ISSUE TITLE
Room number doesn't update

### ISSUE THREAD

**Issue by MichaelWallace30** [MichaelWallace30/schedulerCS356#6]
The meeting information doesn't update when you update the meeting, but if you logout it updates. You should. Change the button name "Create Meeting" it confuses me and will probably confuse Salloum. Maybe like create meeting template or blank meeting. I think Im publishing the meeting when hit the button.

Do you need help implementing the search?

**Comment by CheezBoiger** [comment]
It is updating, but the table view isnt, i am working on that heh.

**Comment by CheezBoiger** [comment]
Yea i am gunna need help on that a bit. Maybe a little object to get queries?

**Comment by MichaelWallace30** [comment]
Might want to narrow the search. What do you want it to find?

**Comment by CheezBoiger** [comment]
What happens is that when you update, the meeting in the database updates, but the table in your display is not constantly checking the db for updates, i would have to keep track of the selected row in the table and update that row when you press the button

**Comment by CheezBoiger** [comment]
What happens is that when you update, the meeting in the database updates, but the table in your display is not constantly checking the db for updates, i would have to keep track of the selected row in the table and update that row when you press the button

**Comment by MichaelWallace30** [comment]
oh just make it update when you hit update on the meeting

**Comment by MichaelWallace30** [comment]
Or use your Observer observable skill son

**Comment by MichaelWallace30** [comment]
I don't have a description on the meetings is that needed? I can add it, but might break a lot of things.

**Comment by CheezBoiger** [comment]
easier said than done mang. I am worried if the user selects a meeting, i need to find the index of that meeting in the tableview (which i have no problem with), but if that user edits that meeting, and decides to sort the tableview, i don't know what will happen.

**Comment by CheezBoiger** [comment]
Yea i don't know why i have the description thing, i thought you did.

**Comment by CheezBoiger** [comment]
Forget the description thing lol

**Comment by CheezBoiger** [comment]
oh wait, i forget that the meetings cells are references lulz. Not too bad then

**Comment by CheezBoiger** [comment]
Oh about the search thing, yes i think the search is only useful for finding meetings based on username, or first name, like to find someone in a meeting.

**Comment by CheezBoiger** [comment]
So say you type in Kittens, the search result will turn up a list of meetings that Kittens is in, or is going to. You can also get the same results if you type Mario Garcia.

**Comment by CheezBoiger** [comment]
So return a list of meetings that the user asked for.

**Comment by CheezBoiger** [comment]
hold on, update table view coming right up.

**Comment by CheezBoiger** [comment]
Forgot, this was fixed lulz.
