### ISSUE TITLE
Rooms don't delete their meeting id, when the meeting is deleted.

### ISSUE THREAD

**Issue by CheezBoiger** [MichaelWallace30/schedulerCS356#9]
Ok, this should be the last thing we need to finish. I need to check the rooms to see if there is any double booking going on in there. The problem is that even though I can add the meeting id into the selected room, I can't remove the meeting from it when either the meeting owner updates the meeting (to another room), or if the owner cancels (deletes) the meeting. Here is the front end code that performs the delete:

``` Java
       // In onRemoveMeeting in UserGUIController.java
      if (meeting != null && success) {
        dbController.updateObject(account);
        boolean removed = dbController.removeObject(meeting);


        if (removed) {
           // Remove the meeting from the room.
          Room room = meeting.getRoom();
          if (room != null) {
            room.removeMeeting(meeting);
            dbController.updateObject(room); // The problem is inside here.
          }

          System.out.println("Removed!");
          meetingData.remove(index);
          updateSidebarMeetings();
        }
      }
```

When the meeting is removed from the list in the room, the updateObject method is called, which in 
turn calls the updateObject method in Room:

``` Java
    @Override
    public Boolean updateObject(DataBaseInterface obj, Connection con)throws SQLException{
        Room room = (Room)obj;
        PreparedStatement ps = con.prepareStatement(
        "UPDATE ROOMS SET DESCRIPTION = ?, MAX_OCCUPANCY = ? WHERE ROOM_NUMBER = ?");

        /*
            THERE IS NO WAY TO REMOVE THE MEETING HERE.


         */
        ListIterator<Meeting> it;
        it = meetingList.listIterator();
        while(it.hasNext()){
            addMeetingTable(con, it.next().getMeetingID()); // Adding, but no removing
        }
        // set the preparedstatement parameters
        ps.setString(1,room.getDescription());
        ps.setInt(2,room.getMaxOccupancy());        
        ps.setInt(3,room.getRoomNumber());

        // call executeUpdate to execute our sql update statement
        // call executeUpdate to execute our sql update statement
        int i = ps.executeUpdate();
        ps.close();   

        if(i <= 0){
        return false;
        }
        return true;
    }
```

This is just to help you with where the problem is, and is in no way trying to make it difficult for you to do this lulz. I keep getting the feeling that I'm pestering you with these bugs lulz.

**Comment by MichaelWallace30** [comment]
Changing rooms still doesn't work you need to add:
room.removeMeeting(meeting);
Some where when you change rooms

When you delete the meeting it works fine though. So assume the code for change room is different.

**Comment by MichaelWallace30** [comment]
Just to be clear this line updates the data base
room.removeMeeting(meeting);

**Comment by MichaelWallace30** [comment]
Just close this one it works or let me know if I need to do more
